---
  - name: Create installation directory
    file: path={{ jdk8_installation_path }}/ state=directory mode=0755

  - name: Install jdk8
    unarchive:
      src: "/home/vagrant/repos/vagrantmachine/roles/jdk8/files/jdk-8u151-linux-x64.tar.gz"
      dest: "{{ jdk8_installation_path }}"
      copy: no
